
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: iris-classifier
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: "2"
      labels:
        apiID: 3a55604eac097a08c83460cecee45fad288445e4298a444f074a3d6e1bc2521
        apiName: iris-classifier
      namespace: default
    spec:
      containers:
      - args:
        - --port=8888
        - --spec=s3://cortex-cluster-vishal/apis/iris-classifier/3a55604eac097a08c83460cecee45fad288445e4298a444f074a3d6e1bc2521/spec.msgpack
        - --cache-dir=/mnt/spec
        - --project-dir=/mnt/project
        env:
        - name: FLASK_ENV
          value: development
        - name: HOST_IP
          value: hello
        - name: MY_PORT
          value: "8888"
        - name: PYTHONUNBUFFERED
          value: "TRUE"
        - name: SPEC
          value: s3://cortex-cluster-vishal/apis/iris-classifier/3a55604eac097a08c83460cecee45fad288445e4298a444f074a3d6e1bc2521/spec.msgpack
        - name: CACHE_DIR
          value: /mnt/spec
        - name: PROJECT_DIR
          value: /mnt/project
        - name: DOWNLOAD_CONFIG
          value: ewogICJkb3dubG9hZF9hcmdzIjogWwogICAgewogICAgICAiZnJvbSI6ICJzMzovL2NvcnRleC1jbHVzdGVyLWRhdmlkL3Byb2plY3RzL2UxODYwNTgwMzE0YmZmMTc1MzViMDQ3NjI4MDQ1NjBhYmI5OTc3MTk5YzI5YTJiMjQxMWM5ZTM1ODVhNTliZC56aXAiLAogICAgICAidG8iOiAiL21udC9wcm9qZWN0IiwKICAgICAgInVuemlwIjogdHJ1ZSwKICAgICAgIml0ZW1fbmFtZSI6ICJ0aGUgcHJvamVjdCBjb2RlIiwKICAgICAgInRmX21vZGVsX3ZlcnNpb25fcmVuYW1lIjogIiIsCiAgICAgICJoaWRlX2Zyb21fbG9nIjogdHJ1ZSwKICAgICAgImhpZGVfdW56aXBwaW5nX2xvZyI6IHRydWUKICAgIH0KICBdLAogICJsYXN0X2xvZyI6ICJwdWxsaW5nIHRoZSBweXRob24gc2VydmluZyBpbWFnZSIKfQ==
        envFrom:
        - configMapRef:
            name: env-vars
        - secretRef:
            name: aws-credentials
        image: 969758392368.dkr.ecr.us-west-2.amazonaws.com/cortexlabs/python-serve:latest
        imagePullPolicy: Always
        name: api
        ports:
        - containerPort: 8888
          protocol: TCP
        readinessProbe:
          httpGet:
            path: "/healthz"
          failureThreshold: 2
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          requests:
            cpu: "0.2"
            memory: "100m"
      # nodeSelector:
      #   workload: "true"
      # imagePullSecrets:
      #   - name: ecr-creds
      serviceAccountName: default
      # tolerations:
      # - effect: NoSchedule
      #   key: workload
      #   operator: Equal
      #   value: "true"
      # - effect: NoSchedule
      #   key: nvidia.com/gpu
      #   operator: Equal
      #   value: "true"
      # - effect: NoExecute
      #   key: node.kubernetes.io/not-ready
      #   operator: Exists
      #   tolerationSeconds: 300
      # - effect: NoExecute
      #   key: node.kubernetes.io/unreachable
      #   operator: Exists
      #   tolerationSeconds: 300
