apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-example-cfg
webhooks:
  - name: mutating-example.cortex.com
    clientConfig:
      url: https://<jumpbox_url>:8889/mutate
      caBundle: $CA_BUNDLE
    rules:
      - operations: [ "*" ]
        apiGroups: ["apps", ""]
        apiVersions: ["v1"]
        resources: ["deployments","services"]
    namespaceSelector:
      matchLabels:
        admission-webhook-example: enabled
